apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-demo-001
  description: RESTful API test
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: borixcr
  system: BKSTG-DEMO
  consumedBy:
    - component: demo-service-001  
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Topics API
      license:
        name: MIT
    servers:
      - url: http://localhost:8080/v1
    paths:
      /topics:
        get:
          summary: List all topics
    
